# Generated by Django 5.0.1 on 2024-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExamApp", "0002_alter_exam_authorphonenum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.TextField()),
                ("image", models.TextField()),
                ("parentQuestionId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=100)),
                ("isCorrect", models.BooleanField()),
                ("parentQuestionId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("grade", models.CharField(max_length=7)),
                ("parentExamId", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="exam",
            name="authorPhoneNum",
            field=models.CharField(max_length=11),
        ),
    ]
