# Generated by Django 5.0.1 on 2024-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=30)),
                ("birthday", models.CharField(max_length=15)),
                ("phoneNumber", models.CharField(max_length=11)),
                ("grade", models.CharField(max_length=7)),
            ],
        ),
    ]
