# Generated by Django 5.0.1 on 2024-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.AlterField(
            model_name="student",
            name="phoneNumber",
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
